/**
 * Conrad Connect PaaS API v1.1.1 - CONFIDENTIAL
 * This document is strictly private, confidential and personal to its recipients and should not be copied, distributed or reproduced in whole or in part, nor passed to any third party. Defines the initial endpoints of the backend supported by CC that are relevant for the PaaS solution. 
 *
 * OpenAPI spec version: 1.1.1-beta2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateTemperatureScheduleBody model module.
* @module model/CreateTemperatureScheduleBody
* @version 1.1.1-beta2
*/
export default class CreateTemperatureScheduleBody {
    /**
    * Constructs a new <code>CreateTemperatureScheduleBody</code>.
    * @alias module:model/CreateTemperatureScheduleBody
    * @class
    * @param device {String} 
    * @param temperatureDelta {Number} 
    * @param startTime {String} Time when the schedule should start in UTC.
    * @param endTime {String} Time when the schedule should end in UTC.
    * @param daysOfWeek {Array.<module:model/CreateTemperatureScheduleBody.DaysOfWeekEnum>} List of weekdays on which the schedule should run.
    */

    constructor(device, temperatureDelta, startTime, endTime, daysOfWeek) {
        
        
        this['device'] = device;
        this['temperatureDelta'] = temperatureDelta;
        this['startTime'] = startTime;
        this['endTime'] = endTime;
        this['daysOfWeek'] = daysOfWeek;
        
    }

    /**
    * Constructs a <code>CreateTemperatureScheduleBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateTemperatureScheduleBody} obj Optional instance to populate.
    * @return {module:model/CreateTemperatureScheduleBody} The populated <code>CreateTemperatureScheduleBody</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTemperatureScheduleBody();
                        
            
            if (data.hasOwnProperty('device')) {
                obj['device'] = ApiClient.convertToType(data['device'], 'String');
            }
            if (data.hasOwnProperty('temperatureDelta')) {
                obj['temperatureDelta'] = ApiClient.convertToType(data['temperatureDelta'], 'Number');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
            if (data.hasOwnProperty('daysOfWeek')) {
                obj['daysOfWeek'] = ApiClient.convertToType(data['daysOfWeek'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} device
    */
    'device' = undefined;
    /**
    * @member {Number} temperatureDelta
    */
    'temperatureDelta' = undefined;
    /**
    * Time when the schedule should start in UTC.
    * @member {String} startTime
    */
    'startTime' = undefined;
    /**
    * Time when the schedule should end in UTC.
    * @member {String} endTime
    */
    'endTime' = undefined;
    /**
    * List of weekdays on which the schedule should run.
    * @member {Array.<module:model/CreateTemperatureScheduleBody.DaysOfWeekEnum>} daysOfWeek
    */
    'daysOfWeek' = undefined;



    /**
    * Allowed values for the <code>daysOfWeek</code> property.
    * @enum {String}
    * @readonly
    */
    static DaysOfWeekEnum = {
        /**
         * value: "Monday"
         * @const
         */
        "Monday": "Monday",
        /**
         * value: "Tuesday"
         * @const
         */
        "Tuesday": "Tuesday",
        /**
         * value: "Wednesday"
         * @const
         */
        "Wednesday": "Wednesday",
        /**
         * value: "Thursday"
         * @const
         */
        "Thursday": "Thursday",
        /**
         * value: "Friday"
         * @const
         */
        "Friday": "Friday",
        /**
         * value: "Saturday"
         * @const
         */
        "Saturday": "Saturday",
        /**
         * value: "Sunday"
         * @const
         */
        "Sunday": "Sunday"    };

}
