/**
 * Conrad Connect PaaS API v1.1.1 - CONFIDENTIAL
 * This document is strictly private, confidential and personal to its recipients and should not be copied, distributed or reproduced in whole or in part, nor passed to any third party. Defines the initial endpoints of the backend supported by CC that are relevant for the PaaS solution. 
 *
 * OpenAPI spec version: 1.1.1-beta2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GetDevicesSummaryResponse model module.
* @module model/GetDevicesSummaryResponse
* @version 1.1.1-beta2
*/
export default class GetDevicesSummaryResponse {
    /**
    * Constructs a new <code>GetDevicesSummaryResponse</code>.
    * @alias module:model/GetDevicesSummaryResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetDevicesSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetDevicesSummaryResponse} obj Optional instance to populate.
    * @return {module:model/GetDevicesSummaryResponse} The populated <code>GetDevicesSummaryResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDevicesSummaryResponse();
                        
            
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], ['String']);
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], ['String']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], ['String']);
            }
        }
        return obj;
    }

    /**
    * List of all types currently in use by the abstraction layer
    * @member {Array.<String>} types
    */
    'types' = undefined;
    /**
    * List of all currently used event names
    * @member {Array.<String>} events
    */
    'events' = undefined;
    /**
    * List of all currently used property names
    * @member {Array.<String>} properties
    */
    'properties' = undefined;




}
