/**
 * Conrad Connect PaaS API v1.1.1 - CONFIDENTIAL
 * This document is strictly private, confidential and personal to its recipients and should not be copied, distributed or reproduced in whole or in part, nor passed to any third party. Defines the initial endpoints of the backend supported by CC that are relevant for the PaaS solution. 
 *
 * OpenAPI spec version: 1.1.1-beta2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProviderInfoAuth from './ProviderInfoAuth';

/**
* The ProviderInfo model module.
* @module model/ProviderInfo
* @version 1.1.1-beta2
*/
export default class ProviderInfo {
    /**
    * Constructs a new <code>ProviderInfo</code>.
    * @alias module:model/ProviderInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ProviderInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProviderInfo} obj Optional instance to populate.
    * @return {module:model/ProviderInfo} The populated <code>ProviderInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProviderInfo();
                        
            
            if (data.hasOwnProperty('auth')) {
                obj['auth'] = ProviderInfoAuth.constructFromObject(data['auth']);
            }
            if (data.hasOwnProperty('authHelper')) {
                obj['authHelper'] = ApiClient.convertToType(data['authHelper'], 'Boolean');
            }
            if (data.hasOwnProperty('b2bOnlyAuth')) {
                obj['b2bOnlyAuth'] = ApiClient.convertToType(data['b2bOnlyAuth'], 'Boolean');
            }
            if (data.hasOwnProperty('documentationUrl')) {
                obj['documentationUrl'] = ApiClient.convertToType(data['documentationUrl'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('logoUrl')) {
                obj['logoUrl'] = ApiClient.convertToType(data['logoUrl'], 'String');
            }
            if (data.hasOwnProperty('plugIconUrl')) {
                obj['plugIconUrl'] = ApiClient.convertToType(data['plugIconUrl'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ProviderInfoAuth} auth
    */
    'auth' = undefined;
    /**
    * true iff a small tutorial for authorization code grant should be shown to the user 
    * @member {Boolean} authHelper
    */
    'authHelper' = undefined;
    /**
    * true iff this provider can only be authenticated by Conrad Connect Professional users 
    * @member {Boolean} b2bOnlyAuth
    */
    'b2bOnlyAuth' = undefined;
    /**
    * @member {String} documentationUrl
    */
    'documentationUrl' = undefined;
    /**
    * Big image that is used for both the provider cards and on the provider page. 
    * @member {String} imageUrl
    */
    'imageUrl' = undefined;
    /**
    * Small logo that is put on the card together with the big image. 
    * @member {String} logoUrl
    */
    'logoUrl' = undefined;
    /**
    * Default image for *plugs*, which are sensors and actuators in the project editor. 
    * @member {String} plugIconUrl
    */
    'plugIconUrl' = undefined;




}
