/**
 * Conrad Connect PaaS API v1.1.1 - CONFIDENTIAL
 * This document is strictly private, confidential and personal to its recipients and should not be copied, distributed or reproduced in whole or in part, nor passed to any third party. Defines the initial endpoints of the backend supported by CC that are relevant for the PaaS solution. 
 *
 * OpenAPI spec version: 1.1.1-beta2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProviderInfo from './ProviderInfo';

/**
* The Provider model module.
* @module model/Provider
* @version 1.1.1-beta2
*/
export default class Provider {
    /**
    * Constructs a new <code>Provider</code>.
    * @alias module:model/Provider
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Provider</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Provider} obj Optional instance to populate.
    * @return {module:model/Provider} The populated <code>Provider</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Provider();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = ProviderInfo.constructFromObject(data['info']);
            }
            if (data.hasOwnProperty('isAuthenticated')) {
                obj['isAuthenticated'] = ApiClient.convertToType(data['isAuthenticated'], 'Boolean');
            }
            if (data.hasOwnProperty('isB2B')) {
                obj['isB2B'] = ApiClient.convertToType(data['isB2B'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('prettyName')) {
                obj['prettyName'] = ApiClient.convertToType(data['prettyName'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Internal name of the provider
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {module:model/Provider.ObjectEnum} object
    */
    'object' = undefined;
    /**
    * @member {module:model/ProviderInfo} info
    */
    'info' = undefined;
    /**
    * true iff the user is authenticated with this provider
    * @member {Boolean} isAuthenticated
    */
    'isAuthenticated' = undefined;
    /**
    * true iff this provider is relevant for Conrad Connect Professional
    * @member {Boolean} isB2B
    */
    'isB2B' = undefined;
    /**
    * Internal name of the provider (same as id)
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Provider name that can be displayed to the user
    * @member {String} prettyName
    */
    'prettyName' = undefined;
    /**
    * A provider of type *device* offers connection to physical devices. A provider of type *service* offers virtual devices like access to APIs. 
    * @member {module:model/Provider.TypeEnum} type
    */
    'type' = undefined;



    /**
    * Allowed values for the <code>object</code> property.
    * @enum {String}
    * @readonly
    */
    static ObjectEnum = {
        /**
         * value: "provider"
         * @const
         */
        "provider": "provider"    };
    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
        /**
         * value: "device"
         * @const
         */
        "device": "device",
        /**
         * value: "service"
         * @const
         */
        "service": "service"    };

}
