/**
 * Conrad Connect PaaS API v1.1.1 - CONFIDENTIAL
 * This document is strictly private, confidential and personal to its recipients and should not be copied, distributed or reproduced in whole or in part, nor passed to any third party. Defines the initial endpoints of the backend supported by CC that are relevant for the PaaS solution. 
 *
 * OpenAPI spec version: 1.1.1-beta2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UserStatistic model module.
* @module model/UserStatistic
* @version 1.1.1-beta2
*/
export default class UserStatistic {
    /**
    * Constructs a new <code>UserStatistic</code>.
    * @alias module:model/UserStatistic
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserStatistic</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserStatistic} obj Optional instance to populate.
    * @return {module:model/UserStatistic} The populated <code>UserStatistic</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserStatistic();
                        
            
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('connectedDevices')) {
                obj['connectedDevices'] = ApiClient.convertToType(data['connectedDevices'], Object);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Number');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }

    /**
    * user's account id, 12 byte BSON string
    * @member {String} account
    */
    'account' = undefined;
    /**
    * map of key-value pairs with provider as key and number of connected devices as value
    * @member {Object} connectedDevices
    */
    'connectedDevices' = undefined;
    /**
    * seconds-based unix timestamp
    * @member {Number} createdAt
    */
    'createdAt' = undefined;
    /**
    * @member {module:model/UserStatistic.ObjectEnum} object
    */
    'object' = undefined;
    /**
    * user's id, 12 byte BSON string
    * @member {String} user
    */
    'user' = undefined;



    /**
    * Allowed values for the <code>object</code> property.
    * @enum {String}
    * @readonly
    */
    static ObjectEnum = {
        /**
         * value: "user-statistic"
         * @const
         */
        "statistic": "user-statistic"    };

}
