/**
 * Conrad Connect PaaS API v1.1.1 - CONFIDENTIAL
 * This document is strictly private, confidential and personal to its recipients and should not be copied, distributed or reproduced in whole or in part, nor passed to any third party. Defines the initial endpoints of the backend supported by CC that are relevant for the PaaS solution. 
 *
 * OpenAPI spec version: 1.1.1-beta2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ExecuteActionButtonProjectBody from '../model/ExecuteActionButtonProjectBody';
import InvalidParameterError from '../model/InvalidParameterError';
import ListActionButtonProjectsResponse from '../model/ListActionButtonProjectsResponse';
import NotFoundError from '../model/NotFoundError';

/**
* ActionButtonInteraction service.
* @module api/ActionButtonInteractionApi
* @version 1.1.1-beta2
*/
export default class ActionButtonInteractionApi {

    /**
    * Constructs a new ActionButtonInteractionApi. 
    * @alias module:api/ActionButtonInteractionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {Object} opts Optional parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    executeActionButtonProjectWithHttpInfo(project, opts) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'project': project
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['accessToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/abstraction/do/{project}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    executeActionButtonProject(project, opts) {
      return this.executeActionButtonProjectWithHttpInfo(project, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListActionButtonProjectsResponse} and HTTP response
     */
    listActionButtonProjectsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['accessToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListActionButtonProjectsResponse;

      return this.apiClient.callApi(
        '/abstraction/do', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListActionButtonProjectsResponse}
     */
    listActionButtonProjects() {
      return this.listActionButtonProjectsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}
